### ISSUE TITLE
Popup Lov pluging Multiple Selection

### ISSUE THREAD

**Issue by jbernal507** [Pretius/Pretius-APEX-Enhanced-Lov-Item#56]
Hi experts 

Im using APEX 18.2 and I m need it to particular functionality of List, return more than one value for example I need to show to end uer at least 6 field in select, and return 4 values to differents apex item before submit... 

any ideas to fix this issue..! 

Thanks a lot..

**Comment by bostrowski** [comment]
Hi @jbernal507 

this functionality is not ready to use out of the box but it can be done via the plug-in configuration.

Imagine your plug-in item is based on emp table and its SQL query looks like below:

```sql
select
  ename d,
  empno||'#'||deptno||'#'||mgr||'#'||job r,
  empno,
  ename,
  deptno,
  mgr,
  job,
  sal,
  comm
from 
  emp
```

It will produce popup report with almost every column from emp table but it will be returning concanated string with values of
- empno
- deptno
- mgr
- job

separated with `#`  character.

When you define dynamic action listening to `change` event on this item you can use true action `Set Value`  to assign these values to items you want.

Lets say you have text items:
- P5_EMPNO
- P5_DEPTNO
- P5_MGR
- P5_JOB

True actions `Set Value` should have attribute `Set Type` set to `JavaScript Expression` and `JavaScript Expression` should look like

```javascript
this.triggeringElement.value.split('#')[0]
```

Where number in square bracket refer index of the value:
- for `empno` its `0`
- for `deptno` its `1`
- for `mgr` its `2`
- for `job` its `3`

True actions should be using `Execution Options \ Fire on Initialization` set to `No` (not checked) so the true action won't be executed on page load.

In general it looks like this:
![image](https://user-images.githubusercontent.com/15342508/83435782-19bd0600-a43d-11ea-95b1-1d8e92dfded2.png)

The end result looks like this:
![example](https://user-images.githubusercontent.com/15342508/83436207-c0a1a200-a43d-11ea-8758-d42e03003052.gif)

Don't forget to set the plug-in attributes so the plug-in popup report won't contain `d` and `r` columns.

**Comment by jbernal507** [comment]
Thanks Bartosz

works great....

**Comment by jbernal507** [comment]
One little thing... 
After submit the apex item keep with the last value... 

![image](https://user-images.githubusercontent.com/66269294/83450936-d1d9b700-a41b-11ea-89ae-b23cf13394da.png)
For example in my case the field is called Order  its OK or I can perform some reset?

**Comment by bostrowski** [comment]
I'm not sure what you are trying to say here

> For example in my case the field is called Order its OK or I can perform some reset?

If you want to clear the field after selecting and redistributing values you can use dynamic action to `Clear` the field.

Please be more specific.

**Comment by jbernal507** [comment]
Thanks Bostrowski... 
OK I said that the field that contain the LOV, after I selected the value, and perform submit the record are insterted into DB, but the filed keep the last value selected..! I would like to crear all fields in the page after submit 

Do you understand me ?

**Comment by jbernal507** [comment]
Hi 
Other main issue its possible that the Plugin allow me to align values of the list for example for amount column  align right? when Show the list 

![image](https://user-images.githubusercontent.com/66269294/83661081-43844300-a58b-11ea-93d2-4379d92b552d.png)

**Comment by bostrowski** [comment]
@jbernal507 

> Thanks Bostrowski...
OK I said that the field that contain the LOV, after I selected the value, and perform submit the record are insterted into DB, but the filed keep the last value selected..! I would like to crear all fields in the page after submit
> Do you understand me ?

yes, you can achieve this by using APEX process called **clear**. You can clear items via dynamic actions, You can clear APEX items from PL/SQL process. All depends on your requirements.

Please spend some time learning APEX. The plug-in support doesn't stand for ask me anything about APEX.

> Hi
> Other main issue its possible that the Plugin allow me to align values of the list for example for amount column align right? when Show the list

Yes, please read the plug-in docs here on github and inline page desinger help/texts for the plug-in attribute **Popup Settings \ Report Columns Configuration**.

I'm closing this thread since the main question is answered.

**Comment by jbernal507** [comment]
OK thanks for your help... 
but all developers can help or not? Now I see that only you answer my questions and its not the idea..!   So I did I posted here to learn from all apex expert..! Then you say some words like " Please spend some time learning APEX. The plug-in support doesn't stand for ask me anything about APEX. "
Of course Im learning but the process is a little slow. 

Thanks for your time and help..! 

regards..!

**Comment by bostrowski** [comment]
@jbernal507 
The case is that this is github repository dedicated to one particular Oracle APEX plug-in. I'm answering because I'm the author of the plug-in and I do support other developers according to the support described in the plug-in readme file.

![image](https://user-images.githubusercontent.com/15342508/84001636-5457fe80-a967-11ea-8452-43f2082cdf27.png)

If you want to learn from APEX developers (world wide) you should consider using apex.world slack or write at official Oracle APEX community forum: https://community.oracle.com/community/groundbreakers/database/developer-tools/application_express

Here I do support Oracle APEX developers only in case they find bug in my plug-in **Pretius APEX Enhanced LOV item**. For example, you found the bug and you want to know when it can be fixed.

Regards
Bartosz
