### ISSUE TITLE
Date Picker Issue

### ISSUE THREAD

**Issue by jbernal507** [Pretius/Pretius-APEX-Enhanced-Lov-Item#57]
Hi Experts 

Im using APEX 18.2 so I have apex item type Date Picker and I need that the end user only can select days of current month? 

All your comments would be appreciate

**Comment by bostrowski** [comment]
change the format mask of an item

![image](https://user-images.githubusercontent.com/15342508/83436609-753bc380-a43e-11ea-9ac9-71850a43faa5.png)

**Comment by jbernal507** [comment]
Hi to all 
The issue is that now with format in DD the END USER can change the month with date picker...So I need that the calendar only show me the current month... for example now we are JUNE only JUNE if the user try to select the next month do nothing or before month nothig else.! 

Show only current month ... 

![image](https://user-images.githubusercontent.com/66269294/83643372-8f2bf200-a575-11ea-8fe1-7358d896801e.png)

**Comment by bostrowski** [comment]
Please spend some time on learning the plug-in capabilities via the included help texts in page designer.

The plug-in attributes allows you to restrict minimum and maximum date. See screenshot below

![image](https://user-images.githubusercontent.com/15342508/83977822-a6673880-a903-11ea-836e-36d0f4b8137a.png)

Items P1_START and P1_END holds first and last day of month returned from PL/SQL.

I'm closing the thread since main and extra questions are answered.
